# Generated by Django 3.2.8 on 2021-10-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='blog/images'),
            preserve_default=False,
        ),
    ]
