# Generated by Django 3.2.4 on 2021-12-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20211217_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Artist', 'Artist'), ('Editor', 'Editor'), ('Admin', 'Admin')], max_length=20)),
                ('user_type_id', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Group', 'Group'), ('Solo', 'Solo')], max_length=50)),
                ('file_no', models.CharField(max_length=50)),
                ('Bank_Name', models.CharField(max_length=100)),
                ('Bank_Account_No', models.CharField(max_length=100)),
                ('Bank_Account_Holder_Name', models.CharField(max_length=100)),
                ('IBAN', models.CharField(max_length=50)),
                ('NIF_No', models.CharField(max_length=50)),
                ('Paypal_Account_No', models.CharField(max_length=50)),
                ('Paypal_Email_Id', models.CharField(max_length=50)),
                ('nationality', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=50)),
                ('distribution_id', models.CharField(choices=[('Ang + Moz', 'Ang + Moz'), ('Mundo', 'Mundo')], max_length=50)),
                ('notes', models.TextField()),
                ('service_in_percentage', models.FloatField(default=50.0)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
