# Generated by Django 3.2.4 on 2021-12-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Bank_Account_Holder_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Bank_Account_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='IBAN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='NIF_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Paypal_Account_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Paypal_Email_Id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='distribution_id',
            field=models.CharField(blank=True, choices=[('Ang + Moz', 'Ang + Moz'), ('Mundo', 'Mundo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='file_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, choices=[('National', 'National'), ('International', 'International')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('Group', 'Group'), ('Solo', 'Solo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Artist', 'Artist'), ('Editor', 'Editor'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
