# Generated by Django 3.2.4 on 2021-12-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211217_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='service_in_percentage',
            field=models.FloatField(blank=True, default=50.0, null=True),
        ),
    ]
